apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"data-profiler-service","namespace":"neuroai-prod"},"spec":{"ports":[{"port":30004,"protocol":"TCP","targetPort":30004}],"selector":{"app":"data-profiler-server"},"sessionAffinity":"None","type":"ClusterIP"}}
  creationTimestamp: "2023-05-16T23:22:22Z"
  name: data-profiler-service
  namespace: neuroai-prod
  resourceVersion: "9227"
  uid: 6d684c22-a18f-4230-b491-42edeba5db31
spec:
  clusterIP: 10.100.149.245
  clusterIPs:
  - 10.100.149.245
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 30004
    protocol: TCP
    targetPort: 30004
  selector:
    app: data-profiler-server
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
