apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"metadata-service","namespace":"neuroai-prod"},"spec":{"ports":[{"port":30001,"protocol":"TCP","targetPort":30001}],"selector":{"app":"metadata-server"},"sessionAffinity":"None","type":"ClusterIP"}}
  creationTimestamp: "2023-05-16T23:22:30Z"
  name: metadata-service
  namespace: neuroai-prod
  resourceVersion: "9295"
  uid: 25c36cc6-cd60-45e2-82c6-9c4f817f7b47
spec:
  clusterIP: 10.100.201.160
  clusterIPs:
  - 10.100.201.160
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 30001
    protocol: TCP
    targetPort: 30001
  selector:
    app: metadata-server
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
