apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"metadata-gateway-service","namespace":"neuroai-prod"},"spec":{"ports":[{"port":30002,"protocol":"TCP","targetPort":30002}],"selector":{"app":"metadata-gateway-server"},"sessionAffinity":"None","type":"ClusterIP"}}
  creationTimestamp: "2023-06-12T21:16:10Z"
  name: metadata-gateway-service
  namespace: neuroai-prod
  resourceVersion: "17699090"
  uid: 57700b36-6a8b-49be-abfc-a6f0882fda2f
spec:
  clusterIP: 10.100.153.229
  clusterIPs:
  - 10.100.153.229
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 30002
    protocol: TCP
    targetPort: 30002
  selector:
    app: metadata-gateway-server
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
