apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"serving-adapter-svc","namespace":"neuroai-prod"},"spec":{"ports":[{"port":30005,"protocol":"TCP","targetPort":"adapter-grpc"}],"selector":{"app":"serving-adapter"},"type":"ClusterIP"}}
  creationTimestamp: "2023-05-16T23:22:44Z"
  name: serving-adapter-svc
  namespace: neuroai-prod
  resourceVersion: "9417"
  uid: dfcb095e-1227-4e77-94b0-fd8f71f002d8
spec:
  clusterIP: 10.100.239.151
  clusterIPs:
  - 10.100.239.151
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 30005
    protocol: TCP
    targetPort: adapter-grpc
  selector:
    app: serving-adapter
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
