apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"labels":{"app":"secrets-manager"},"name":"secrets-manager-deployment","namespace":"neuroai-prod"},"spec":{"replicas":1,"revisionHistoryLimit":10,"selector":{"matchLabels":{"app":"secrets-manager"}},"strategy":{"rollingUpdate":{"maxSurge":"25%","maxUnavailable":"25%"},"type":"RollingUpdate"},"template":{"metadata":{"labels":{"app":"secrets-manager"}},"spec":{"automountServiceAccountToken":true,"containers":[{"env":null,"image":"634208487213.dkr.ecr.us-west-2.amazonaws.com/leaf/unileaf-secrets-manager:3219a7031ce52f557014d1670eab8d11e03ea4be","imagePullPolicy":"Always","name":"secrets-manager","resources":{"limits":{"cpu":"1","memory":"8Gi"}},"terminationMessagePath":"/prod/termination-log","terminationMessagePolicy":"File"}],"dnsPolicy":"ClusterFirst","nodeSelector":{"kubernetes.io/os":"linux"},"restartPolicy":"Always","schedulerName":"default-scheduler","securityContext":{},"serviceAccount":"unileaf-account","serviceAccountName":"unileaf-account","terminationGracePeriodSeconds":30}}}}
  creationTimestamp: "2023-06-01T14:54:33Z"
  generation: 1
  labels:
    app: secrets-manager
  name: secrets-manager-deployment
  namespace: neuroai-prod
  resourceVersion: "10204553"
  uid: 2e7b6e1c-f6e6-48ff-8d4e-19f51e3c2cc3
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: secrets-manager
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: secrets-manager
    spec:
      automountServiceAccountToken: true
      containers:
      - image: 634208487213.dkr.ecr.us-west-2.amazonaws.com/leaf/unileaf-secrets-manager:3219a7031ce52f557014d1670eab8d11e03ea4be
        imagePullPolicy: Always
        name: secrets-manager
        resources:
          limits:
            cpu: "1"
            memory: 8Gi
        terminationMessagePath: /prod/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      nodeSelector:
        kubernetes.io/os: linux
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: unileaf-account
      serviceAccountName: unileaf-account
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2023-06-01T15:55:27Z"
    lastUpdateTime: "2023-06-01T15:55:27Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2023-06-01T15:55:27Z"
    lastUpdateTime: "2023-06-01T15:55:27Z"
    message: ReplicaSet "secrets-manager-deployment-6dc98d9f84" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
